name: Run Pytest with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# ✅ allow pushing the Allure report to gh-pages
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # Checkout Repository
      # ---------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ---------------------------
      # Setup Python
      # ---------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ---------------------------
      # Install Dependencies
      # ---------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest selenium

      # ---------------------------
      # Run Pytest in Headless Mode
      # ---------------------------
      - name: Run Pytest
        run: |
          pytest --headless -v --alluredir=allure-results || true

      # ---------------------------
      # Generate Allure Report
      # ---------------------------
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.8
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      # ---------------------------
      # Configure Git Identity
      # ---------------------------
      - name: Configure Git identity
        run: |
          git config --global user.email "varshithaperam27@gmail.com"
          git config --global user.name "varshiii27"

      # ---------------------------
      # Deploy Allure Report to GitHub Pages
      # ---------------------------
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
