name: Run Pytest with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # Checkout Repository
      # ---------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ---------------------------
      # Setup Python
      # ---------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ---------------------------
      # Install Dependencies
      # ---------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest selenium webdriver-manager

      # ---------------------------
      # Install Browsers
      # ---------------------------
      - name: Install Browsers
        run: |
          sudo apt update
          sudo apt install -y chromium-browser firefox geckodriver microsoft-edge-stable

      # ---------------------------
      # Download Allure Commandline
      # ---------------------------
      - name: Download Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.zip -O allure.zip
          unzip allure.zip -d $HOME/allure
          export PATH="$HOME/allure/allure-2.35.1/bin:$PATH"
          allure --version

      # ---------------------------
      # Run Pytest in Headless Mode
      # ---------------------------
      - name: Run Pytest
        run: |
          pytest -v --alluredir=allure-results

      # ---------------------------
      # Generate Allure Report
      # ---------------------------
      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean

      # ---------------------------
      # Configure Git Identity
      # ---------------------------
      - name: Configure Git identity
        run: |
          git config --global user.email "varshithaperam27@gmail.com"
          git config --global user.name "varshiii27"

      # ---------------------------
      # Deploy Allure Report to GitHub Pages
      # ---------------------------
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
