name: Run Pytest with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest selenium

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-commandline.zip -O allure.zip
          unzip allure.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-*/bin/allure /usr/bin/allure

      - name: Run Pytest
        run: |
          pytest -v --alluredir=allure-results || true

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Configure Git identity
        run: |
          git config --global user.email "varshithaperam27@gmail.com"
          git config --global user.name "varshiii27"

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
